### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by playboi080385** [haad/proxychains#114]
had a very similar problem, mine denied when i added a proxychains the socks4 125.26.99.228
commented out the strict put dynamic, commit out the remote, went to test "proxychains firefox google.com 
nothing i get a error access denied -443 firefox times out like it should although at the end says" need more proxys "  i did RTFM obviously. but their is no reason for that. why would it give me that  error.

**Comment by sell1ng** [comment]
try running sudo apt update or just completely use a different proxy
