### ISSUE TITLE
please tell me what to do i have done almost everything i could

### ISSUE THREAD

**Issue by Pheonix244001** [haad/proxychains#116]
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/x86_64-linux-gnu/libproxychains.so.4
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] DLL init: proxychains-ng 4.14
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  127.0.0.1:9050 <--denied
^CExiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.
Exiting due to channel error.

**Comment by ahmii1234** [comment]
Comment out the strict chain in the conf file and un comment for example dynamic chain add another socks proxy server socks4 is added by default and try again.

**Comment by sell1ng** [comment]
if you're on linux, head to your terminal and type in "sudo vim /etc/proxychains.conf" then, add a "#" next to strict_chain. and remove the "#" next to dynamic_chain to enable proxychains to run in that mode. if you have any problem  configuring the controls in vim, do some research on the controls

**Comment by sell1ng** [comment]
hopefully my comment helped.

**Comment by AustinRhoads** [comment]
I had the same problem even after commenting out the strict line. any ideas?

**Comment by DerFuhrerVonDeutschland** [comment]
do the command: sudo nano /etc/proxychains.conf
then add at the bottom: socks5 127.0.0.1 9050
after that do ctrl+x and type: systemctl start tor
and then after that do the command: proxychains firerfox google.com 
hopefully my comment worked

**Comment by Yonkokaido123** [comment]
yoo i have the same problem any ideas????

**Comment by Christophrenic** [comment]
This issue persists for me on Ubuntu 22.04.3 LTS

Strict is commented, dynamic is uncommented, proxychains include SOCK4 and SOCK5 127.0.0.1:9050
No other service other than tor is using port 9050.  System time is configured correctly. Tor is confirmed to be running. Yet proxychains does not work.
