### ISSUE TITLE
Is there anyone knows how to 'traceroute' over proxies?

### ISSUE THREAD

**Issue by Allgot** [haad/proxychains#149]
Hello.

Currently I'm trying to traceroute over the proxy which supports SOCKS(4, 5) and HTTP protocol.

However it doesn't seem to work properly...
Here is how I tried:
`sudo proxychains traceroute --tcp www.google.com`
`sudo proxychains traceroute --udp www.google.com`
`sudo proxychains traceroute www.google.com`

And how I configured(/etc/proxychains.conf):
`
...
socks5 {IP} {PORT} {USERNAME} {PASSWORD}
`
I also tried using socks4 and http too.

Is there anyone knows how to do traceroute in such cases?

**Comment by ValdikSS** [comment]
You can't. Traceroute is based on the fact that you send the IP packets with low TTL and increase it gradually. No proxy protocol support manipulation of TTL field.

**Comment by Allgot** [comment]
Ohh... I didn't know about it at all. Then the only way to traceroute remotly is using VPN services, rather than proxies?

**Comment by ValdikSS** [comment]
Yes.

**Comment by Allgot** [comment]
Thanks!
