### ISSUE TITLE
proxychains nginx not work

### ISSUE THREAD

**Issue by 1101302428** [haad/proxychains#151]
proxychains nginx it's always connect timeout, but proxychains curl is working

**Comment by NoobforAl** [comment]
I have same problem! 
First I think this nginx problem but it's not!
[stackoverflow question](https://stackoverflow.com/questions/77609376/proxychians-for-nginx)

**Comment by wello07** [comment]
hello, am trying to use proxychains but for some reason it ain't working and giving me socket error and time out, some 
times it says denied is there a way to fix that problem ?
