### ISSUE TITLE
using golang  and  proxychains  aren't working

### ISSUE THREAD

**Issue by Dillon86** [haad/proxychains#154]
I wrote one golang script like below
`
package main
import (
        "fmt"
        "golang.org/x/crypto/ssh"
        "log"
        "time"
)

func main() {
        // SSH连接配置
        config := &ssh.ClientConfig{
                User: "user",
                Auth: []ssh.AuthMethod{
                        ssh.Password("password"),
                },
                Timeout:         30 * time.Second,
                HostKeyCallback: ssh.InsecureIgnoreHostKey(),
        }

        // 连接SSH服务器
        client, err := ssh.Dial("tcp", "ip:22", config)
        if err != nil {
                log.Fatalf("Failed to dial: %s", err)
        }

        // 执行命令
        session, err := client.NewSession()
        if err != nil {
                log.Fatalf("Failed to create session: %s", err)
        }
        defer session.Close()

        // 在这里可以执行需要保持连接的操作，例如发送命令、接收输出等
        // 下面是一个简单的示例，发送一个命令并打印输出
        cmd := "ping -c 30 www.google.com"
        output, err := session.Output(cmd)
        if err != nil {
                log.Fatalf("Failed to execute command: %s", err)
        }
        fmt.Println(string(output))
}
`
I build the script with command `go build check.go`,after this. I run command like this`proxychains4 ./check` .

I checked the result by `netstat` for checking port connection . proxychains4 isn't using.but `proxychains4 curl ifconfig.me` working

I don't understand.

**Comment by zhangw** [comment]
You must know that proxychains only works on hacking "system libc".
As I known, the "system libc" linked dynamically on macOS for golang prog. (in that case, it works!)
But on linux, the "system libc" not linked dynamically (golang itself implement connect, read, recvfrom... syscalls that could not by hacking via proxychains)
