### ISSUE TITLE
proxychains don't work with brave

### ISSUE THREAD

**Issue by Lunasciel** [haad/proxychains#159]
**Describe the bug**
proxychains works with firefox but do not with brave

**To Reproduce**
1. Run command: proxychains brave

**Expected behavior**
no problems and starting without problems

**Additional context**
LOG:
[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[0202/112334.629102:WARNING:close_multiple.cc(67)] close: Bad file descriptor (9)
[0202/112334.629146:WARNING:close_multiple.cc(67)] close: Bad file descriptor (9)
[0202/112334.629148:WARNING:close_multiple.cc(67)] close: Bad file descriptor (9)
[0202/112334.629151:WARNING:close_multiple.cc(67)] close: Bad file descriptor (9)
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[proxychains] DLL init: proxychains-ng 4.17
[2445:2445:0202/112334.845809:FATAL:zygote_host_impl_linux.cc(217)] Check failed: . : No such file or directory (2)
Trace/breakpoint trap (core dumped)

**Comment by jolucas245** [comment]
What is your distro and the installation method you used (distro repository or makefile)?

**Comment by Lunasciel** [comment]
I am using brave with arch and paru ^^

**Comment by jolucas245** [comment]
Use the make install installation according to the steps in the repository: 
`git clone https://github.com/haad/proxychains`
`./configure`
`make`
`sudo make install`

**Comment by Lunasciel** [comment]
Now the browser opens and after opening it this message appears in the console:

```
ProxyChains-4.0 (https://github.com/haad/proxychains)
Proxified environment setup
PROXYCHAINS_CONF_FILE = 
LD_PRELOAD = 
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Opening in existing browser session.
```

The funny thing is it still doesn't work, because the DNS leak test still shows my correct location, even though I have Tor and the service is running in the background, unless I've misunderstood. Also, I'm not sure which 'proxychain' config I should use, the one in /dist or /src? The problem is not brave either, as I have also tested chromium and the cachy-brower... what am I doing wrong?
