### ISSUE TITLE
cannot make on kubuntu 15.10

### ISSUE THREAD

**Issue by felicitywang** [haad/proxychains#49]
This is what I got:
fay@kubuntu:~/downloads/proxychains-master$ ./configure
Linux
done, now run make && make install
fay@kubuntu:~/downloads/proxychains-master$ make
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror   -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/core.o src/core.c
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror   -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/common.o src/common.c
cc -Wall -O2 -g -std=c99 -D_GNU_SOURCE -pipe -DTHREAD_SAFE -Werror   -DLIB_DIR=\"/usr/local/lib\" -DINSTALL_PREFIX=\"/usr/local\" -DDLL_NAME=\"libproxychains4.so\" -DSYSCONFDIR=\"/usr/local/etc\"  -fPIC -c -o src/libproxychains.o src/libproxychains.c
cc -shared -fPIC  -pthread -ldl -Wl,--no-as-needed -install_name,libproxychains4.so -o libproxychains4.so src/core.o src/common.o src/libproxychains.o
cc: error: unrecognized command line option ‘-install_name,libproxychains4.so’
Makefile:66: recipe for target 'libproxychains4.so' failed
make: **\* [libproxychains4.so] Error 1

**Comment by yzld2002** [comment]
the same to me

**Comment by aki237** [comment]
Try removing the 
```make
$(LD_SET_SONAME)$(LDSO_PATHNAME)
```
from 66th line in Make file after configuring

66th:
```Make
$(LDSO_PATHNAME): $(LOBJS)                                                    
        $(CC) $(LDFLAGS) $(LD_SET_SONAME)$(LDSO_PATHNAME) -o $@ $(LOBJS)
```
It compiled successfully for me.
