### ISSUE TITLE
Execute bash file without proxychains

### ISSUE THREAD

**Issue by justas05** [haad/proxychains#64]
Structure:
    script1.sh (launches script2.sh)
    script2.sh

Launch:
    proxychains ./script1.sh

script2.sh must be executed without proxychain.
How to do it?

**Comment by kem008** [comment]
If u dont want proxychain just dont use it. Xdddd dunno why u need multiple shell

**Comment by OptiMysticall** [comment]
just put "proxychains ./script2.sh" in script1.sh.. or however you're launching script2

**Comment by justas05** [comment]
Closed
