### ISSUE TITLE
proxychains and support of the docker command

### ISSUE THREAD

**Issue by hsafe** [haad/proxychains#68]
Hi,
It is super helpful if the proxychains allows us in Embargoed countries pull docker images....Docker site bans us to get the images while not behind any vpn or proxy.  While my proxychians works flawlessly behind the tor network to for example get youtube videos or simple wget and curl ,it fails to docker pull images... is there a trick to it?, or simply it can't work with docker pull?
I compiled the proxychains from the latest source and one line config basic that tries socks5 to localhost on default tor port. Please note as said there is no issue with other commands and proxychains behaves as expected...:( Thank you for your help...

**Comment by emranbm** [comment]
Any update on this?
