### ISSUE TITLE
 ld.so: object 'libproxychains.so' from LD_PRELOAD cannot be preloaded

### ISSUE THREAD

**Issue by sheepdestroyer** [haad/proxychains#7]
hi,
using the last git on fedora 16 64bit i get the following error when using proxychains :

ERROR: ld.so: object 'ERROR: ld.so: object 'libproxychains.so' from LD_PRELOAD cannot be preloaded: ignored.

still, the program seems to work ok.

**Comment by gptlang** [comment]
Many years later, I still seem to be getting this warning:
```
ERROR: ld.so: object 'libproxychains.so.4' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
