### ISSUE TITLE
[patch] - prng seed

### ISSUE THREAD

**Issue by audibleblink** [haad/proxychains#72]
Hey, would you be interested in a PR for the way the prng is seeded when using `random_chain`?

I noticed when using random_chain with a tool whose requests return quicker than a second, the same proxy can be selected for subsequent requests. With something like wfuzz or hydra, you can sometimes get between 3-10 requests going out through the same proxy. The patch below remedies that. 

https://github.com/audibleblink/proxychains/commit/2a577f19f39e4f8293d998167cfddb4c26ab5bc9

My C is awful, as you can see, but it works so that every request uses a new proxy (barring the occasional bad roll). What do you think?

**Comment by haad** [comment]
sure but as you can see I don't have much time to maintain proxychains anymore so I can make you committer if you want.

**Comment by audibleblink** [comment]
that works for me. thanks.
