### ISSUE TITLE
This account has been hacked. This issue was not opened by the account owner. The account owner is currently working to reclaim this account. Please ignore this issue.  Sorry for any inconvenience, and thank you for your support.

### ISSUE THREAD

**Issue by AwesomePenguin** [haad/proxychains#78]
This account has been hacked. This issue was not opened by the account owner. The account owner is currently working to reclaim this account. Please ignore this issue.

Sorry for any inconvenience, and thank you for your support.

**Comment by hunjixin** [comment]
the same problem
