### ISSUE TITLE
Suppress proxychains message

### ISSUE THREAD

**Issue by dclong** [haad/proxychains#79]
ProxyChains output some message like the below. How can I suppress this message?
```
ProxyChains-?-? (http://proxychains.sf.net)
```

**Comment by nbbm26** [comment]
couple options using nohup:
`man nohup`
first option with logging output replacing [] with command and args you want followed by second [] where you name the file for logged output to be saved
`nohup proxychains [command with args as normal] &> [name of file to log output]&`
`nohup proxychains [command with args as normal] </dev/null >/dev/null 2>&1 &`

example:
`nohup proxychains youtube-dl https://www.youtube.com/watch?v=VeAK7Bv4F1o </dev/null >/dev/null 2>&1 &`

**Comment by AlexanderSerov** [comment]
proxychains4 supports quite mode
```
./proxychains4

Usage:  proxychains4 -q -f config_file program_name [arguments]
        -q makes proxychains quiet - this overrides the config setting
        -f allows to manually specify a configfile to use
        for example : proxychains telnet somehost.com
More help in README file
```
