### ISSUE TITLE
whitelist for proxy

### ISSUE THREAD

**Issue by c625473164** [haad/proxychains#90]
How shold I config if I only want to redirect http reqeusts on a single ip:port such as localhost:8080

**Comment by OptiMysticall** [comment]
You would remove every proxy in the ProxyyList section and add 
Proxytype(HTTP,HTTPS,SOCKS4,SOCKS5)   ip for localhost  8080
HTTP                                                                     127.0.0.1     8080
HTTP                                                                     127.0.0.1     8080
HTTP                                                                     127.0.0.1     8080
THen set the uncomment the line for random_chain then set chain_len to 1.

This will help if there is a failure, it will essentially retry. 
Then these values should be something reasonable like:
tcp_read_time_out 20000
tcp_connect_time_out 15000


This assumes you're running something on localhost port 8080 that will forward connections out.. like a Tor proxy. However Tor uses socks.. https://www.linuxuprising.com/2018/10/how-to-install-and-use-tor-as-proxy-in.html
