### ISSUE TITLE
Can't load process ./libproxychains4.so

### ISSUE THREAD

**Issue by mydockergit** [haad/proxychains#93]
I downloaded the latest release.  
I followed the instructions:  
```
./configure
make
sudo make install
```
I ran:
`./proxychains4 -f ./proxychains.conf target.com`

I received the following errors:  
```
[proxychains] config file found: ./proxychains.conf
[proxychains] preloading ./libproxychains4.so
proxychains can't load process....: No such file or directory
```

But when I run `ls` I have the file `libproxychains4.so` so I don't understand what is the problem?

**Comment by cheng-tony** [comment]
Hi, I have same problem
I found that there's a bug here!!
the index of "LD_LIBS" searching

>        
        i=0;   // [SOL] init the index here!!!
	while(dll_dirs[i]) {   // bug !!! the index start of 1
		snprintf(buf, sizeof(buf), "%s/%s", dll_dirs[i], dll_name);
		if(access(buf, R_OK) != -1) {
			prefix = dll_dirs[i];
			break;
		}
		i++;
	}
